#!/bin/bash
# ClaudeOS PR Generator — WorkTree 連動 PR 自動生成
# Usage: ./create-pr.sh [title] [body]
#
# 自動検出: 現在のブランチ名、変更ファイル数、コミット数

set -euo pipefail

BRANCH=$(git branch --show-current)
BASE="${BASE_BRANCH:-main}"

if [ "$BRANCH" = "$BASE" ]; then
  echo "ERROR: Cannot create PR from $BASE branch. Switch to a feature branch." >&2
  exit 1
fi

# 既存 PR チェック
EXISTING_PR=$(gh pr list --head "$BRANCH" --json number -q '.[0].number' 2>/dev/null || echo "")
if [ -n "$EXISTING_PR" ]; then
  echo "SKIP: PR already exists: #$EXISTING_PR for branch $BRANCH" >&2
  echo "$EXISTING_PR"
  exit 0
fi

# 変更情報を自動収集
COMMIT_COUNT=$(git rev-list --count "$BASE..$BRANCH" 2>/dev/null || echo "0")
CHANGED_FILES=$(git diff --stat "$BASE..$BRANCH" 2>/dev/null | tail -1 || echo "no changes")
COMMIT_SUBJECTS=$(git log --oneline "$BASE..$BRANCH" 2>/dev/null | head -10 || echo "")

# タイトル（引数 or 自動生成）
TITLE="${1:-Auto PR: $BRANCH}"

# ボディ（引数 or 自動生成）
if [ -n "${2:-}" ]; then
  BODY="$2"
else
  BODY="## Summary
Auto-generated by ClaudeOS

## Changes
- Branch: \`$BRANCH\`
- Commits: $COMMIT_COUNT
- $CHANGED_FILES

## Commits
\`\`\`
$COMMIT_SUBJECTS
\`\`\`

## Test
- Pending CI verification

🤖 Generated with ClaudeOS"
fi

PR_URL=$(gh pr create \
  --title "$TITLE" \
  --body "$BODY" \
  --base "$BASE" \
  --head "$BRANCH" 2>/dev/null)

PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
echo "OK: Created PR #$PR_NUMBER: $TITLE"
echo "$PR_NUMBER"
