#!/bin/bash
# ClaudeOS Issue Generator — 自動 Issue 生成
# Usage: ./create-issue.sh <title> [body] [labels]
#
# トリガー: TODO検出, FIXME検出, CI失敗, テスト不足

set -euo pipefail

TITLE="${1:?Usage: create-issue.sh <title> [body] [labels]}"
BODY="${2:-Auto-generated by ClaudeOS Dev Factory}"
LABELS="${3:-auto-generated}"

# 重複チェック（同一タイトルの open Issue がないか）
EXISTING=$(gh issue list --state open --search "$TITLE" --json number,title -q \
  ".[] | select(.title == \"$TITLE\") | .number" 2>/dev/null || echo "")

if [ -n "$EXISTING" ]; then
  echo "SKIP: Issue already exists: #$EXISTING '$TITLE'" >&2
  echo "$EXISTING"
  exit 0
fi

# Issue 作成
ISSUE_URL=$(gh issue create \
  --title "$TITLE" \
  --body "$BODY" \
  --label "$LABELS" 2>/dev/null)

ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oE '[0-9]+$')
echo "OK: Created Issue #$ISSUE_NUMBER: $TITLE"
echo "$ISSUE_NUMBER"
